# Rota Data Lancamento
GET http://localhost:3000/jogos?dataLancamento=2000

###

# Rota Data Lancamento Maior ou Menor
GET http://localhost:3000/jogos?dataLancamento=2000&dataMaior=true

###

# Rota Para Buscar Determinado Jogo Pelo Titulo
GET http://localhost:3000/jogos?titulo=Valorant

###

# Rota Para Buscar Determinado Atributo de um Jogo
GET http://localhost:3000/jogos/Valorant?atributo=genero

###

POST http://localhost:3000/database
Content-Type: application/json

{
    "nome": "Davi Siqueira"
}